#! /usr/bin/env bash

build=--dev

[ "$1" = --dev ] && { build=--dev; shift; }
[ "$1" = --prod ] && { build=--prod; shift; }

./scripts/compile.sh $build || exit $?

if (( $# == 0 )); then
  find spec -type f -iname "*.spec.sh" | xargs ./vendor/microspec
else
  ./vendor/microspec "$@"
fi