#! /usr/bin/env bash

export EXPECT_BUILD=--dev

[ "$1" = --dev ] && { EXPECT_BUILD=--dev; shift; }
[ "$1" = --prod ] && { EXPECT_BUILD=--prod; shift; }

./scripts/compile.sh $EXPECT_BUILD || exit $?

if (( $# == 0 )); then
  find spec -type f -iname "*.spec.sh" | xargs ./vendor/microspec
else
  ./vendor/microspec "$@"
fi