title: "Expect"
description: '🧐 expect { BASH testing } toBe "lovely"'
theme: jekyll-theme-slate
markdown: kramdown
show_downloads: true
twitter_username: rebeccca_taylor
github_username: beccasaurus

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github:
  zip_url: https://github.com/specs-sh/expect/archive/v2.0.0.zip
  tar_url: https://github.com/specs-sh/expect/archive/v2.0.0.tar.gz
  owner_url: https://github.com/beccasaurus
  owner_name: "@beccasaurus"

markdown: kramdown
kramdown:
  parse_block_html: true

defaults:
  -
    values:
      layout: default

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock